language: csharp

mono:
 - 4.4.1

os:
 - osx
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: libsodium-net.sln

install:
 - nuget restore libsodium-net.sln
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

before_script:
 - bash travis-build-libsodium.sh

script:
 - xbuild libsodium-net.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/bin/Debug/Tests.dll
